Interface for integration - method registerOnTakedHandler
MissCorruption/QuickLootIE pull request #37
Opened 2024-07-15 22:16 UTC by AndbGame

WIP, not ready for merge. But Review will be nice

2024-07-17 15:37 UTC, MissCorruption reviewed
This is mainly formatting and notes on the upcoming rewrite

2024-07-17 15:37 UTC, MissCorruption commented on include/QuickLootIEInterface.h
> +			GROUNG = 1,
Typo, it should be ground

2024-07-17 15:37 UTC, MissCorruption commented on include/QuickLootIEInterface.h
> +		struct TakedItem
`Taked` is grammatically wrong, Taken would be correct, but TakenItem sounds odd.

2024-07-17 15:37 UTC, MissCorruption commented on include/QuickLootIEInterface.h
> +			std::vector<TakedItem> items;
See the previous comment

2024-07-17 15:37 UTC, MissCorruption commented on src/Integrations/QuickLootInterfaceImpl.cpp
> +	using OnTakedHandler = QuickLootIE::QuickLootIEInterface::OnTakedHandler;
The `Taked` sounds wrong here

2024-07-17 15:37 UTC, MissCorruption commented on src/Items/OldGroundItems.h
This file will be removed at a later date, with a coming rewrite. It'll be a while until then, but still

2024-07-17 15:37 UTC, MissCorruption commented on src/Items/OldInventoryItem.h
This will also be removed or rather replaced at a later date

2024-07-17 15:37 UTC, MissCorruption commented on src/XSEPlugin.cpp
> +#include "Integrations/QuickLootInterfaceImpl.h"
Just being pedantic here, but I'd like those to be in order. I.e. Integrations and then Papyrus

2024-07-17 15:37 UTC, MissCorruption commented on include/QuickLootIEInterface.h
> +namespace QuickLootIE
This should be QuickLoot, not QuickLootIE. IE should never appear in code. A good class name would be `QuickLoot::Integrations::QuickLootAPI`

2024-07-17 21:17 UTC, AtomCrafty commented on src/Integrations/QuickLootInterfaceImpl.cpp
> +	bool QuickLootInterfaceImpl::handleOnTaked(TakedEvent evt)
Our naming convention is to also capitalize private function names.

2024-07-23 19:59 UTC, AndbGame commented
wow, thank you, for such a number of comments, I will definitely sort them out :)

2024-07-23 20:11 UTC, AndbGame commented on src/Integrations/QuickLootInterfaceImpl.cpp
> +		switch (a_msg->type) {
I have planned and plan to integrate through Request/ResponseServer

But I found a problem in:
```
	class RequestServer
	...
		void RegisterHandler(uint32_t requestType, const char* name, QueryHandler<TRequest, TResponse> handler)
		{
			static_assert(std::is_trivial_v<TRequest>, "Request data must be trivial.");
			static_assert(std::is_trivial_v<TResponse>, "Regular handlers can only handle trivial response data. Use string handlers to return strings.");
```

and since the interface is not a trivial type (it is a class/struct with functions/pointers to functions) - it is not allow me use `TResponse` for pass interface

2024-07-23 20:17 UTC, AtomCrafty commented on src/Integrations/QuickLootInterfaceImpl.cpp
> +		switch (a_msg->type) {
Yes, that is intentional. Passing an instance of a non-trivial type is forbidden, since everything sent through this mechanism is passed by value. Trying to pass a class instance would result in a potentially unsafe memcopy of the class fields. Instead of the instance itself you would send a pointer to it. The pointer is a trivial type.

However as I mentioned in other comments, I don't think the interface needs to exist at all.

2024-07-23 20:33 UTC, AtomCrafty commented on src/Integrations/QuickLootInterfaceImpl.cpp
> +		switch (a_msg->type) {
Actually no, I just checked the code again and it's not passed by value. I put that check in there specifically to prevent users from passing `std::string`, `std::vector` or other STL class instances since that is inherently unsafe.

The ability to pass user defined classes didn't seem like a useful feature and I still don't think it's needed. As I noted above, it's possible to circumvent the safeguard by passing a pointer instead. Note that a class passed this way must not accept or return any STL containers.

If you take a look at Completionist.h, which is the client for the API implemented by Faen, you'll see that the "interface" is basically just a number of static functions which internally call the `RequestClient`. That is the only communication channel between the two mods. Your case is a bit more complicated since you are actually registering a callback, which is a second channel, and one that doesn't have any safeguards in place. Make sure that none of the data structures passed to or from the callback contain any STL containers.

2024-07-31 23:04 UTC, AndbGame commented
in my opinion, I have taken into account all the comments, it is also not ready for Merge yet, I am in thought..., and I am in absolutely no hurry (especially in light of the ongoing refactoring and the lack of time :( ), but there maybe conceptual remarks for this

2024-08-03 09:59 UTC, AndbGame commented
What am I thinking about now:

Implemented:

`OnTakenHandler` - Event fired after take some item from container in QuickLoot UI
```
		struct TakenEvent
		{
			RE::Actor* actor;
			Element* elements;
			std::size_t elementsCount;
			RE::TESObjectREFR* container;
			RE::TESForm* containerOwner;
			bool isStealAlarm;

                        // TODO: variant 1
                       Element* remainingEements;
		       std::size_t remainingEementsCount;

                        // TODO: variant 2 (the container has become empty)
                       bool isLast;
		};
```
Looks I am need information about last taked element from container (Container is empty)

2024-08-03 10:09 UTC, AndbGame commented
Additional Api methods (I'm not sure yet, maybe I should reject some methods)

- `OnTakedHandler`/`OnAttemptToTakeHandler` - the difference from the `OnTakenHandler` is that this method can return `kStop`, and quickloot in this case must reject take this element - restriction mechanism.... 
but there may be a very controversial solution that is easy to get around if you open the container in a native/game way... But we can also implement rejection mechanism(and api) for dissalow open container in a native/game way
but there may be a very controversial solution that is easy to get around if you open the container in a native/game way... But we can also implement rejection mechanism(and api) for restrict opening container in a native/game way (but restriction for specific item and whole container - it is different things)

2024-08-03 10:15 UTC, AndbGame commented
- `onHoverHandler`/`onSelectHandler` - fired when some item is selected in UI: another mod can use it for some 'notification' - if you take this item - something might happen.
Also (but not sure) - this handlers can return some customization info - for customize UI - change background color of selected item, etc...

2024-08-03 10:21 UTC, AndbGame commented
> Additional 2 Api methods (I'm not sure yet, maybe I should reject some methods)
> 
> * `OnTakedHandler`/`OnAttemptToTakeHandler` - the difference from the `OnTakenHandler` is that this method can return `kStop`, and quickloot in this case must reject take this element - restriction mechanism....
> 
> but there may be a very controversial solution that is easy to get around if you open the container in a native/game way... But we can also implement rejection mechanism(and api) for restrict opening container in a native/game way (but restriction for specific item and whole container - it is different things)

2024-08-04 20:55 UTC, AtomCrafty commented
Regarding `OnAttemptToTake`: That sounds a lot like a concept commonly known as [preview events](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/events/preview-events?view=netdesktop-8.0). WPF nomenclature would be `Take`/`PreviewTake`, but other frameworks sometimes use `Take`/`Taking`, where `Taking` is the name of the preview event. The preview event handlers can cancel the whole operation.

I agree that these would be useful events to have:
- `Take`/`Taking`
- `Open`/`Opening`
- `Close` (no preview event)
- `Select` (no preview event)

I don't think we need to add customizable background colors, but the `Select` handler could provide data for the item info bar. The info bar is currently unused, but its purpose is to show additional information for the selected item in the blank space to the right of the weight info.

2024-08-04 21:31 UTC, AndbGame commented
So, I have committed 3 events for now:

1. `TakenHandler` - notify when and what user take from UI
2. `SelectHandler` - notify when and what selected in UI
3. `LootMenuHandler` (3 Status: OPEN, CLOSE, INVALIDATE): OPEN, CLOSE - notify when UI opening or closing, INVALIDATE - when itemList is changed (and which items is present in UI)

---

For now, looks such events is enough for simple integration (enough for my goals :) )

Conceptually, everything looks like it's quite workable, I've done the basic functionality of my addon, and everything seems to be OK, but now I want to focus more on it, maybe I'll find some problems

But the question of naming and additional refactoring not closed


Regarding `OnAttemptToTake` and other methods, which change behavior of QuickLoot - is more complicated - need additional refactoring in QuickLoot code

I do not completely refuse, but not in the current MR. (maybe after additional MR with refactoring/ some implementations). Changing the logic of the mod is a little more difficult task, I think, because it can cause bugs, so I'll postpone it for now.

Within the current MR, I will limit myself to simple events - notifications (maybe it is will be enought for first version of API)

2024-08-04 21:39 UTC, AndbGame commented
> LootMenuHandler (3 Status: OPEN, CLOSE, INVALIDATE): OPEN, CLOSE - notify when UI opening or closing, INVALIDATE - when itemList is changed (and which items is present in UI)

I think I've assigned too many responsibilities to one handler :)

2024-08-13 14:10 UTC, AndbGame commented
At the moment, everything looks like it's ready.

An example of how I use it at the moment can be seen here: https://github.com/AndbGame/QuickLootIE-DD/blob/main/src/InterfaceQuickLootIE.cpp

Next step: I am waiting refactoring PR

2024-08-13 17:46 UTC, MissCorruption commented
The refactor might take a long while, if you consider this feature complete and working, I'd merge it. Crafty mentioned that they'll adjust the rewrite accordingly

2024-08-14 00:48 UTC, AtomCrafty requested changes
Looks good for the most part. Thanks for putting all this work into it!

I've suggested some changes regarding names and type hierarchy, as well as some architectural changes I'd implement. Mostly things to reduce duplicated code.

I've implemented most of this feedback in [my local version](https://github.com/AtomCrafty/QuickLootIE/commits/interface/) of your branch.
If you want you can just copy my changes to your working tree like this:

```
git stash
git remote add atomcrafty https://github.com/AtomCrafty/QuickLootIE.git
git fetch atomcrafty
git rebase atomcrafty/interface
git stash pop
```

My version also adds all of the infrastructure for the `TakingItem` event, although at this time it is never invoked.

2024-08-14 06:44 UTC, AndbGame commented on include/QuickLootIntegrations.h
> +		RE::TESObjectREFR* container = nullptr;
In fact, for me this is a rather incomprehensible question
based on the logic of GroundItems - not all items can belong to a container. And I still haven't decided what to do about it. And based on logic, there are 2 possible options:
1) `event.Element.container = event.container` - It is Inventory Item
2) `event.Element.container = nullptr` - It is Ground Item

Whether this information might be needed for integration - is a question - I couldn't figure out how to use it. 
And to avoid confusion - in general, I see no reason not to delete it - if everyone agrees

2024-08-14 06:46 UTC, AndbGame commented on include/QuickLootIntegrations.h
> +			RE::TESObjectREFR* container = nullptr;
looks mistake... need remove

2024-08-14 11:44 UTC, AndbGame commented on include/QuickLootIntegrations.h
> +	namespace TakeHandler
Yes. this solution is more elegant!

2024-08-14 12:24 UTC, AndbGame commented on include/QuickLootIntegrations.h
> +			return true;
Yes, I think this is my mistake, need return `response`

in general, I have been thinking about whether there are situations when registering a new handler may be unsuccessful

For example: allow register new handlers only in process, when SKSE is initializing
or allow dynamic registration/unregistration handlers - but it is overhead for required thread safe mechanism, etc...

so I discard this - and the correct practice for registering new handlers should be a process in which SKSE process messages, (and maybe before load any save/new game) - but all this is at the discretion of the mod, which needs integration (but need to keep in mind that the process is not thread safe)

2024-08-14 12:33 UTC, AndbGame commented on src/Integrations/PluginServer.cpp
> +	inline bool PluginServer::RegisterOnTakeHandler(TakeHandler::OnTakeHandler handler)
I myself was wondering how the compiler would work, and I double-checked this point in IDA, and found that compiler inline this function only after I specify `inline`. 

But in fact, the function is not performance-critical, and `inline` is absolutely not necessary.

2024-08-14 12:35 UTC, AndbGame commented on src/Integrations/PluginServer.cpp
> +		evt.container = container.get() ? container.get().get() : nullptr;
ok. I didn't know for sure, and I was probably overly cautious.

2024-08-14 12:44 UTC, AndbGame commented on include/QuickLootIntegrations.h
> +		static bool RegisterTakeHandler(TakeHandler::OnTakeHandler handler)
yes, it makes sense

2024-08-14 14:10 UTC, AtomCrafty commented on include/QuickLootIntegrations.h
> +		RE::TESObjectREFR* container = nullptr;
Okay, that makes it clearer. So currently it is essentially just a boolean to indicate whether the item is in the inventory or on the ground. That's fine then.

2024-08-14 14:12 UTC, AtomCrafty commented on include/QuickLootIntegrations.h
> +			return true;
Right, I thought about thread safety for a moment as well, but forgot about it again. Maybe we should add a lock guard around the list accesses?

2024-08-14 14:13 UTC, AtomCrafty commented on src/Integrations/PluginServer.cpp
> +	inline bool PluginServer::RegisterOnTakeHandler(TakeHandler::OnTakeHandler handler)
I'm surprised that's how it behaves, but I stand corrected. In that case I don't mind keeping it.

2024-08-14 15:24 UTC, AndbGame commented on src/Integrations/PluginServer.h
> +		static inline PluginRequests::RequestServer GetRequestServer() { return _server; };
Oh. thanks. A vivid example of what happens when a web/php developer programs in c++ :D

2024-08-14 15:32 UTC, AndbGame commented on include/QuickLootIntegrations.h
> +		{
I thought this was redundant information, since the UI cannot be open to multiple containers at the same time, but at the same time I have no objections, perhaps in some use cases it is necessary...

2024-08-14 15:35 UTC, AtomCrafty commented on include/QuickLootIntegrations.h
> +		{
Another mod might want to do some processing on the container when the loot menu closes. Of course it could save the container from the open event and use it in the close event, but it's easier if we just include the container in the close event as well.

2024-08-14 15:39 UTC, AndbGame commented on include/QuickLootIntegrations.h
> +		{
I remembered: maybe also need remove actor from events?
is there any theoretical possibility that some day there will be some kind of logic, in which actor may differ from Palyer?
I can't think of a possible scenario when it is will be required...

2024-08-14 15:42 UTC, AtomCrafty commented on include/QuickLootIntegrations.h
> +		{
I don't think the actor will ever be different from the player. The QuickLoot implementation uses the global player character singleton in all sorts of places and I don't think that will change anytime soon.

2024-08-14 15:45 UTC, AndbGame commented
Thank you for the work done! I am definitely merge it.

2024-08-14 15:56 UTC, AtomCrafty approved these changes

2024-08-14 16:33 UTC, MissCorruption commented
Good job you two! I'm going to merge this then

2024-08-14 16:33 UTC, merged

2024-08-14 22:55 UTC, AndbGame commented
@MissCorruption thanks! :)

Looks only question about thread safety has not been fully resolved. But also, by my mind - not have any problems with the current implementation

`std::vector` as I understand is thread safe for read

But:
1. We can prevent adding new handlers (modify `*Handlers`) after kPostLoadGame/kNewGame
2. Add lock guard for `RegisterHandler`

but it is unclear how appropriate this is, perhaps this is an excessive 'defense mechanism'